version: '3.7'

services:
   console:
      container_name: yannick-console-dev
      hostname: console-dev.local
      build:
         context: .
      working_dir: /src
      volumes:
         - ..:/src:cached
      command: >
         bash -c "sleep infinity"
      networks:
         yannick:

networks:
   yannick:
